[package]
name = "rep_cxl"
version = "0.1.0"
edition = "2021"
default-run = "rep_cxl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.44"
libc = "0.2.175"
log = "0.4.27"
simple_logger = "5.0.0"
