[package]
name = "rep_cxl"
version = "0.1.0"
edition = "2021"
default-run = "rep_bench"

[dependencies]
clap = { version = "4.5.44", features = ["string"] }
libc = "0.2.175"
log = "0.4.27"
rand = "0.9.2"
serde = { version = "1", features = ["derive"] }
simple_logger = "5.0.0"
toml = "0.8"
