# RepCXL configuration file
# Example usage: <binary> -c config/example.toml

########## RepCXL global parameters
mem_nodes = ["/dev/shm/repCXLnode0", "/dev/shm/repCXLnode1"] # List of memory nodes (required in practice)
mem_size = 1048576 # 1 MiB
chunk_size = 64 # 64 bytes
id = 0 # Unique identifier for the repCXL instance (required in practice)
processes = 1 # Number of total repCXL processes in the cluster
round_time = 1000000 # (ns) Duration of the synchronous round (in nanoseconds)
# Replication algorithm: "monster", "sync_best_effort", "async_best_effort"
algorithm = "monster"

